### [전체 목차](../../README.md)
### [이전 페이지](../README.md)

# 5 일차
예외처리

## 목차

- [Exception handling](#exception-handling)
- [finally](#finally)
- [Exception 발생 시키기](#exception-발생-시키기)
    - [raise 구문](#raise-구문)

## [Exception handling](#목차)
Exception을 처리해서 정상화 시키는 작업

```python
try:
    Exception 발생가능한 코드 블록
except [Exception클래스 이름 [as 변수]] :
    처리 코드   
```

- **except block**
    - 모든 Exception을 처리하는 경우 `except:` 로 선언한다.
    - 특정 Exception만 따로 처리할 경우 `except Exception 클래스 이름` 을 선언한다.
        
```python
# try - except
print("시작") # 1.

try:
    num = int(input()) # 2.
    result = 10 // num # 3.
    print("결과:", result) # 4.
    
except ValueError: # except Exception 이름 => Exception 이름의 예외만 처리
    print("실행도중 ValueError 발생했습니다.") # 예외처리

except ZeroDivisionError:
    print("실행도중 ZeroDivisionError 발생함.")

except: # 위 두개 Exception을 제외한 나머지 Exception을 처리하는 block
    print("ValueError, ZDE 이외의 예외가 발생함.")

print("프로그램 종료") # 5.
```

- 예외가 발생하지 않은 경우 실행 순서
    - 1 => 2 => 3 => 4 => 5 ('예외처리'는 실행이 안됨)
- 예외가 발생한 경우
    - 2번 라인에서 발생
        - 1 => 2(x) => 예외처리 => 5
        - 실행 안된 라인: 2, 3, 4
    - 3번 라인에서 발생
        - 0을 입력하면 3번에서 에러 발생

## [finally](#목차)

- 예외 발생여부와 관계없이 무조건 실행되는 코드블록
    - try 구문에 **반드시 실행되야 하는 코드블록을 작성할때 사용한다.**
    - 구문순서: try - except - finally  

```py
print("시작")
try:
    print(1)
    print(2)
    print(aaa) # type: ignore
except NameError:
    print(3)
finally:
    print("정상코드-반드시 실행되야함.")
print("종료")

> 시작
> 1
> 2
> 3
> 정상코드-반드시 실행되야함.
> 종료
```

```py
# run.py 파일과 연결해서 그 안의 text를 읽기.
try:
    # 1. 파일과 연결 => 사용
    fr = open("run.py", encoding="UTF-8")
    # 2. 읽기
    txt = fr.read()
    print(txt) # 사용
except:
    print("처리")
finally:
    # 3. 연결 끊기(닫기) => 사용종료
    fr.close()
```

## [Exception 발생 시키기](#목차)

- Exception 상황을 클래스로 정의해 사용한다.
- `Exception` 클래스를 **상속받는다.**

```py
# 월 1 ~ 12 이외의 값이 대입됐을 때 발생시킬 Exception 클래스 정의
class InvalidMonthException(Exception):

    def __init__(self, invalid_month):
        # Exception이 발생된 상황과 관련된 값들을 초기화
        self.invalid_month = invalid_month

    def __str__(self):
        # 오류 메시지를 문자열로 반환
        return f"{self.invalid_month}는 잘못된 월입니다. 1 ~ 12 사이의 값을 넣으세요."

# Exception 발생
raise InvalidMonthException(500)
```

- 함수나 메소드가 더 이상 작업을 진행할 수 없는 조건이 되면 Exception을 강제로 발생시킨다.
- **Call Stack Mechanism**
    - 발생한 Exception은 처리를 하지 않으면 caller에게 전달된다.
    - 발생한 Exception에 대한 처리가 모든 caller에서 안되면 프로그램은 비정상적으로 종료된다.

```py
# call stack mechanism
def a():
    print("a시작")
    b()
    print("a종료")

def b():
    print("b시작")
    try:
        c()
    except:
        print("처리=========")
    print("b종료")

def c():
    print("c시작")
    print(1/0)
    print("c종료")

if __name__ == "__main__":
    a()

> a시작
> b시작
> c시작
> 처리=========
> b종료
> a종료
```

### [raise 구문](#목차)

- Exception을 강제로 발생시킨다.

    ```python
        raise Exception객체
    ```

- **raise와 return**
    - 함수나 메소드에서 return과 raise 구문이 실행되면 모두 caller로 돌아간다.
    - return: 정상적으로 끝나서 돌아가는 의미이다.
        - caller는 그 다음 작업을 이어서 하면 된다.
    - raise: 실행도중 Exception이 생겨 비정상적으로 끝나서 돌아가는 의미이다.
        - 비정상적인 상황 정보를 가지는 Exception 객체를 가지고 돌아간다.
        - caller는 exception을 처리하여 프로그램을 정상화 한다.

```py  
def save_month(month):
    """월을 저장하는 함수
    Parameter:
        month: int - 저장할 월. 1 ~ 12
    Return:
    Raise:
        InvalidMonthException - 잘못된 월을 받았을 때 발생
    """
    if month < 1 or month > 12:
        # print("저장할 수 없음")
        raise InvalidMonthException(month) # return은 정상적으로 마무리했다는 의미 -> 다음 작업 day가 수행됨
    else:
        print(f"월로 {month}를 저장합니다.")

def save_day(day):
    print(f"일로 {day}를 저장합니다.")
```

```py
save_month(10)
> 월로 10를 저장합니다.

save_day(3)
> 일로 3를 저장합니다.
```

```py
try:
    save_month(-10)
    save_day(3)
except InvalidMonthException as e: # e: 발생된 Exception 객체를 받을 변수
    print('처리', e)

print("다음 작업")

> 처리 -10는 잘못된 월입니다. 1 ~ 12 사이의 값을 넣으세요.
> 다음 작업
```


### [목차로 돌아가기](#목차)
## [이전 페이지](../README.md)
